CREATE TABLE TMESSAGE (
  FID         INTEGER      NOT NULL,
  FTIME       TIMESTAMPTZ,
  FREGTIME    TIMESTAMPTZ,
  FISONLINE   BOOLEAN,
  FISSERVICE  BOOLEAN,
  FALARMLEVEL SMALLINT,
  FPIORITY    SMALLINT,
  FMESSID     VARCHAR(150) NOT NULL,
  FCODE       VARCHAR(150) NOT NULL,
  FSOBJECT    VARCHAR(150),
  FCOBJECT    VARCHAR(150),
  CONSTRAINT PK_TMESSAGE PRIMARY KEY (FID),
  CONSTRAINT UK_TMESSAGE_ID UNIQUE (FMESSID)
);